products:
  - name: "Kanjivaram Silk Saree"
    price: "149.99"
    description: "A stunning Kanjivaram silk saree, renowned for its rich colors and intricate zari work. Perfect for weddings and special occasions."
    images: 
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-1.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-2.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-3.jpg?v=1714812817&width=600"

  - name: "Banarasi Brocade Saree"
    price: "139.99"
    description: "Elegant Banarasi brocade saree with elaborate motifs and a luxurious feel. A perfect choice for festive celebrations."
    images:
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-1.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-2.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-3.jpg?v=1714812817&width=600"

  - name: "Chiffon Printed Saree"
    price: "69.99"
    description: "Lightweight chiffon saree with vibrant prints, ideal for summer outings. Easy to drape and comfortable to wear."
    images:
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-1.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-2.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-3.jpg?v=1714812817&width=600"

  - name: "Georgette Embroidered Saree"
    price: "89.99"
    description: "Beautiful georgette saree featuring intricate embroidery. Perfect for evening events and parties."
    images:
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-1.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-2.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-3.jpg?v=1714812817&width=600"

  - name: "Cotton Handloom Saree"
    price: "49.99"
    description: "Soft and breathable handloom cotton saree, perfect for daily wear. A blend of comfort and traditional elegance."
    images:
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-1.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-2.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-3.jpg?v=1714812817&width=600"

  - name: "Net Lace Saree"
    price: "99.99"
    description: "Stylish net lace saree adorned with delicate lace work. Ideal for cocktail parties and evening gatherings."
    images:
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-1.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-2.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-3.jpg?v=1714812817&width=600"

  - name: "Satin Saree with Sequin Work"
    price: "119.99"
    description: "Luxurious satin saree embellished with sequins for a glamorous look. Perfect for festive occasions and celebrations."
    images:
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-1.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-2.jpg?v=1714812817&width=600"
      - "https://www.studio149fashion.com/cdn/shop/files/ATHUL-1-3.jpg?v=1714812817&width=600"
